ConfigPath = "/Users/cloudy/Documents/go/src/github.com/itcloudy/base-framework/config/config.toml"
DBUpdateToVersion = ""
JwtPrivatePath = "/Users/cloudy/Documents/go/src/github.com/itcloudy/base-framework/config/jwt/tm.rsa"
JwtPublicPath = "/Users/cloudy/Documents/go/src/github.com/itcloudy/base-framework/config/jwt/tm.rsa.pub"
LockFilePath = "/Users/cloudy/Documents/go/src/github.com/itcloudy/base-framework/system-data/base-framework.lock"
Mode = "debug"
PidFilePath = "/Users/cloudy/Documents/go/src/github.com/itcloudy/base-framework/system-data/base-framework.pid"
SystemDataDir = "/Users/cloudy/Documents/go/src/github.com/itcloudy/base-framework/system-data"
TempDir = "/Users/cloudy/Documents/go/src/github.com/itcloudy/base-framework/framework-temp"
TokenExpire = "2h0m0s"
UserDataDir = "/Users/cloudy/Documents/go/src/github.com/itcloudy/base-framework/user-data"

[Centrifugo]
  Enable = false
  Secret = "127.0.0.1"
  URL = "127.0.0.1"

[Cors]
  AllowCredentials = true
  AllowHeaders = ["Authorization","Content-Length","X-CSRF-Token","Accept","Origin","Host","Connection","Accept-Encoding","Accept-Language","DNT","X-CustomHeader","Keep-Alive","User-Agent","X-Requested-With","If-Modified-Since","Cache-Control","Content-Type","Pragma"]
  AllowMethods = ["POST","PUT","GET","DELETE","OPTIONS"]
  AllowOrigins = ["*"]
  AllowWebSockets = true
  ExposeHeaders = ["Authorization","Content-Length","X-CSRF-Token","Accept","Origin","Host","Connection","Accept-Encoding","Accept-Language","DNT","X-CustomHeader","Keep-Alive","User-Agent","X-Requested-With","If-Modified-Since","Cache-Control","Content-Type","Pragma"]
  MaxAge = "12h0m0s"

[DB]
  Charset = "utf8"
  DbType = "postgres"
  Host = "127.0.0.1"
  LockTimeout = 5000
  Name = "go"
  Password = "postgres"
  Port = 5432
  User = "postgres"

[EmailNotification]
  Enable = false
  From = ""
  Host = "smtp.qq.com"
  Password = ""
  Port = 0
  Subject = ""
  To = ""
  Username = ""

[HTTP]
  Enable = true
  Host = "127.0.0.1"
  Port = 8000

[Log]
  Compress = true
  EnableKafka = false
  FileName = "/Users/cloudy/Documents/go/src/github.com/itcloudy/base-framework/system-data/base-framework.log"
  KafkaAddress = ["localhost:9092"]
  MaxAge = 7
  MaxBackups = 3
  MaxSize = 1024

[RPC]
  Enable = true
  Host = "127.0.0.1"
  Port = 9000

[Redis]
  Addr = "localhost:6379"
  DB = 0
  Enable = false
  Password = ""

[TLS]
  CertFile = "/Users/cloudy/Documents/go/src/github.com/itcloudy/base-framework/config/https/cert.pem"
  Enable = false
  KeyFile = "/Users/cloudy/Documents/go/src/github.com/itcloudy/base-framework/config/https/key.pem"
